from typing import Any, Callable, Iterator, Optional

class StixError(Exception): ...
class ParseError(StixError): ...
class ModelError(StixError): ...
class MatchError(StixError): ...
class ValidationError(StixError): ...

class Pattern:
    @property
    def ast(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class Bundle:
    def object_count(self) -> int: ...
    def __len__(self) -> int: ...
    def object(self, index: int) -> Optional[dict[str, Any]]: ...
    def __iter__(self) -> Iterator[dict[str, Any]]: ...

class MatchResult:
    @property
    def matched(self) -> bool: ...
    @property
    def observations(self) -> list[int]: ...
    def __bool__(self) -> bool: ...

class Engine:
    def __init__(self) -> None: ...
    def parse_pattern(self, src: str) -> Pattern: ...
    def parse_bundle(self, json: str) -> Bundle: ...
    def match_bundle(self, pattern: Pattern, bundle: Bundle) -> MatchResult: ...
    def register_type(
        self, type_name: str, hook: Callable[[dict[str, Any]], dict[str, Any]]
    ) -> None: ...
